#!/bin/sh
set -e

# top-level
git submodule update --init rocket-chip riscv-tools testchipip hwacha torture
# rocket-chip (skip tools)
git -C rocket-chip submodule update --init --recursive hardfloat chisel3 firrtl
# esp-tools (skip llvm)
git -C riscv-tools submodule update --init --recursive riscv-isa-sim riscv-fesvr riscv-pk riscv-opcodes riscv-tests riscv-gnu-toolchain riscv-openocd
# torture submodules
git -C torture submodule update --init --recursive
